INSERT INTO user(id, email, name, created_at, updated_at, deleted_at) VALUES
   (1, 'user1@example.com', 'User1', NOW(), NOW(), NULL),
   (2, 'user2@example.com', 'User2', NOW(), NOW(), NULL),
   (3, 'user3@example.com', 'User3', NOW(), NOW(), NULL),
   (4, 'user4@example.com', 'User4', NOW(), NOW(), NULL),
   (5, 'user5@example.com', 'User5', NOW(), NOW(), NULL),
   (6, 'user6@example.com', 'User6', NOW(), NOW(), NULL),
   (7, 'user7@example.com', 'User7', NOW(), NOW(), NULL),
   (8, 'user8@example.com', 'User8', NOW(), NOW(), NULL),
   (9, 'user9@example.com', 'User9', NOW(), NOW(), NULL),
   (10, 'user10@example.com', 'User10', NOW(), NOW(), NULL),
   (11, 'user11@example.com', 'User11', NOW(), NOW(), NULL),
   (12, 'user12@example.com', 'User12', NOW(), NOW(), NULL),
   (13, 'user13@example.com', 'User13', NOW(), NOW(), NULL),
   (14, 'user14@example.com', 'User14', NOW(), NOW(), NULL),
   (15, 'user15@example.com', 'User15', NOW(), NOW(), NULL),
   (16, 'user16@example.com', 'User16', NOW(), NOW(), NULL),
   (17, 'user17@example.com', 'User17', NOW(), NOW(), NULL),
   (18, 'user18@example.com', 'User18', NOW(), NOW(), NULL),
   (19, 'user19@example.com', 'User19', NOW(), NOW(), NULL),
   (20, 'user20@example.com', 'User20', NOW(), NOW(), NULL);

INSERT INTO memo(id, content, created_at, updated_at, deleted_at, user_id) VALUES
(1, '장 볼 것 리스트: 우유, 계란, 빵', NOW(), NOW(), NULL,1),
(2, '읽을 책 목록: 해리포터, 반지의 제왕', NOW(), NOW(), NULL,1),
(3, '운동 계획: 스쿼트, 런닝, 풀업', NOW(), NOW(), NULL,1),
(4, '학습 계획: 파이썬, 자바, 스프링 부트', NOW(), NOW(), NULL,1),
(5, '관광 계획: 제주도, 부산, 강릉', NOW(), NOW(), NULL,2),
(6, '영화 목록: 인셉션, 매트릭스, 스타워즈', NOW(), NOW(), NULL,2),
(7, '책 목록: 코스모스, 흔한남매, 나미야 잡화점의 기적', NOW(), NOW(), NULL,2),
(8, '음식 목록: 피자, 치킨, 햄버거', NOW(), NOW(), NULL,2),
(9, '주말 계획: 산책, 요가, 게임', NOW(), NOW(), NULL,2),
(10, '쇼핑 목록: 옷, 신발, 가방', NOW(), NOW(), NULL,2),
(11, '회사 업무: 보고서 작성, 회의 참석, 프로젝트 관리', NOW(), NOW(), NULL,2),
(12, '개발 공부: 리액트, 노드, 루비', NOW(), NOW(), NULL,3),
(13, '여행 계획: 파리, 런던, 도쿄', NOW(), NOW(), NULL,3),
(14, '운동 계획: 요가, 플라잉 요가, 수영', NOW(), NOW(), NULL,3),
(15, '뮤지컬 목록: 렌트, 위키드, 맘마미아', NOW(), NOW(), NULL,3),
(16, '레시피: 김치찌개, 된장찌개, 순두부찌개', NOW(), NOW(), NULL,3),
(17, '일기: 오늘은 좋은 하루였다.', NOW(), NOW(), NULL,3),
(18, '독서 목록: 해리포터, 반지의 제왕, 나니아 연대기', NOW(), NOW(), NULL,4),
(19, '가족 계획: 가족 나들이, 가족 여행', NOW(), NOW(), NULL,4),
(20, '영어 공부: 단어 암기, 문법 공부', NOW(), NOW(), NULL,4);
